name = "JuliaCompare"
uuid = "3d8d4ae5-8408-43be-a011-487a2b51b31b"
authors = ["Peter Volkmar (Purple) <pnvolkmar@gmail.com>"]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
CategoricalArrays = "324d7699-5711-5eae-9e2f-1d82baa6b597"
Chain = "8be319e6-bccf-4806-a6f7-6fae938471bc"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataFramesMeta = "1313f7d8-7da2-5740-9ea0-a2ca25f37964"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
PromulaDBA = "60a444bf-242d-4d42-8b8e-182a32c45738"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
